name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

                  - name: Setup Java JDK
                  
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'adopt'
          
      - name: Start Minecraft server
        run: |
          java -Xmx1024M -Xms1024M -jar server.jar nogui
