name: Keep Replit Site Alive

on:
  push:
    branches:
      - main

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request to Replit Site
        run: curl -s https://replit.com/@1saad1ahmad1/Minecraft-Afk-Bot
        continue-on-error: true
        timeout-minutes: 1
        if: always()
