name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to use the latest version of actions/checkout

      - name: Set up Java
        uses: actions/setup-java@v3  # Update to use the latest version of actions/setup-java
        with:
          distribution: 'adopt'
          java-version: '21'  # Install Java 21 for running the Minecraft server

      - name: Start Minecraft server
        run: |
          import java.net.InetAddress;
import java.net.UnknownHostException;

public class Main {
    public static void main(String[] args) {
        try {
            InetAddress ipAddress = InetAddress.getLocalHost();
            String ip = ipAddress.getHostAddress();
            int port = 25565; // Assuming default Minecraft server port is 25565
            System.out.println("Server IP address: " + ip);
            System.out.println("Server port: " + port);
        } catch (UnknownHostException e) {
            System.err.println("Unable to determine IP address: " + e.getMessage());
        }
    }
}

          java -Xmx1024M -Xms1024M -jar server.jar nogui
