name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Minecraft Server Setup
        env:
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          # Get the IP address dynamically
          IP_ADDRESS=$(hostname -I | cut -d' ' -f1)
          echo "Server IP address: $IP_ADDRESS"
          PORT=$(netstat -tlnp | awk '/docker-proxy/ && /LISTEN/ {split($4,a,":"); print a[length(a)]}')
          echo "Port number: $PORT"
          echo "Server is listening on port: $PORT"
          # Additional setup commands for starting the Minecraft server
          java -Xmx1024M -Xms1024M -jar server.jar nogui
