name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to use the latest version of actions/checkout

      - name: Set up Java
        uses: actions/setup-java@v3  # Update to use the latest version of actions/setup-java
        with:
          distribution: 'adopt'
          java-version: '21'  # Install Java 21 for running the Minecraft server

      - name: Minecraft Server Setup
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          echo "Server IP address: $SERVER_IP"
          echo "Server port: $SERVER_PORT"

          # Additional setup commands for starting the Minecraft server
          java -Xmx1024M -Xms1024M -jar server.jar nogui
